###############################################################
# Author(s):
#     Juhapekka Piiroinen <juhapekka.piiroinen@csc.fi>
#
# License: MIT
#
# (C) 2019 Copyright CSC – IT CENTER FOR SCIENCE LTD.
# All Rights Reserved.
###############################################################
---
- name: Run letsencrypt certbot
  become: yes
  shell: |
    yum install -y augeas
    pip install -U pip
    pip install certbot certbot-apache
    pip install -U setuptools
  args:
    executable: /bin/bash
  
- name: Run letsencrypt certbot
  become: yes
  shell: |
    certbot -n certonly --agree-tos --email hostmaster@{{ apache2.serverName }} --apache -w /var/www -d {{ apache2.serverName }}
  args:
    creates: "/etc/letsencrypt/live/{{ apache2.serverName }}"
    executable: /bin/bash

