###############################################################
# Author(s):
#     Juhapekka Piiroinen <juhapekka.piiroinen@csc.fi>
#
# License: MIT
#
# (C) 2019 Copyright CSC – IT CENTER FOR SCIENCE LTD.
# All Rights Reserved.
###############################################################
---
- name: Docker-compose | Install dependencies
  shell: yum install -y epel-release python-pip
  become: yes

- name: Docker-compose | Install
  shell: pip install docker-compose
  become: yes

- name: Docker-compose | Ensure that all python packages are up to date.
  shell: yum upgrade -y python*
  become: yes

- name: Docker-compose | Try to use
  shell: docker-compose version
